#Option 1: for cloud subscription
# FROM jfrog.vcloud.local.jfrog.io/docker-quickstart/ubuntu:16.04
#Option 2: for Self-Hosted subscription. Remove the above cloud command and use the below command
FROM jfrog.vcloud.local:8082/docker-quickstart/ubuntu:16.04
CMD printf "CONGRATULATIONS!!! You have just set up your first Docker repository with the new JFrog Platform!"
